# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d8008371047179829e88e7521f054f18f75a55c98e87dbf5ffcd172e1050c739f6cc3c0f40767c3f06da2fc77887bfe63d8fde14e52ff69e6e2a44dd416db3

test:
  secret_key_base: 7825b4b32736b68f98ba0906b6923b6cff6d92964826f0bf692131dfdba59017e32664b46930dceb3923cdb636286a25beacf014557269bc0708198c8d48f0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
